version: "3.7"
services:
  db:
    image: mysql/mysql-server:5.7
    container_name: board-mysql
#    ports:
#    - "3306:3306"
    environment:
      MYSQL_USER: "jutabi"
      MYSQL_PASSWORD: "test1234"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "Board_development"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
#      --default-authentication-plugin=mysql_native_password
    volumes:
    - /Rails_Project/db-data:/var/lib/mysql
#    - /etc/localtime:/etc/localtime:ro

  rails:
    container_name: board-rails
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "80:80"
    depends_on:
      - db