version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - add_ssh_keys:
          fingerprints:
            - "2f:97:29:23:08:c3:84:22:5f:eb:83:cd:c8:5a:0c:ff"
      - run:
          name: ssh echo
          command: ssh -o StrictHostKeyChecking=no root@106.10.36.29 -p 1024 "echo hello"
#      - ruby/bundle-install

workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            only: master