FROM mysql/mysql:8.0

ENV MYSQL_USER jutabi
ENV MYSQL_PASSWORD test1234
ENV MYSQL_ROOT_PASSWORD password
#ENV MYSQL_DATABASE visitlog


# docker run -d -p 3306:3306
    #-e MYSQL_ROOT_PASSWORD=password
    #--name board-mysql
    #--network rails_network
    #-v /home/ec2-user/db:/var/lib/mysql mysql/mysql-server:8.0
    #--character-set-server=utf8mb4
    #--collation-server=utf8mb4_unicode_ci

    #test